name: yeeo
description: A new Flutter application.

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  easy_localization: ^2.3.2
  shared_preferences: ^0.5.4+3
  flare_flutter: 2.0.2
  cupertino_icons: ^0.1.2
  page_transition: ^1.1.4
  image_picker: 0.6.5+3
  provider: 4.3.2
  image_cropper: ^1.1.0
  responsive_widgets: ^2.0.1
  flutter_phoenix: ^1.0.0
  auto_size_text: ^2.1.0
  flutter_svg: ^0.22.0
dev_dependencies:
  flutter_native_splash: ^1.1.8+4
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.9.0
flutter_icons:
  android: "launcher_icon"
  ios: false
  image_path_android: "assets/images/icon.png"
  image_path_ios: "assets/images/icon.png"

flutter_native_splash:
  color: "#ffffff"
  image: assets/images/splash.png
  ios_content_mode: scaleToFill
  android_gravity: fill
flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/flrs/
    - assets/
    - translations/
    - assets/fonts/

  fonts:
    - family: Salsa-Regular
      fonts:
        - asset: assets/fonts/Salsa-Regular.ttf
    - family: Tharlon-Regular
      fonts:
        - asset: assets/fonts/Tharlon-Regular.ttf
    - family: Shrikhand-Regular
      fonts:
        - asset: assets/fonts/Shrikhand-Regular.ttf
